[workspace]
members = [
    "tools",
    "shared",
    "bootloader",
    "kernel",
    "kernel/volatile_field",
    "kernel/pci_types",
    "kernel/apic",
    "kernel/xhci",
    "kernel/usb-xhci",
]
resolver = "2"
