[workspace]
members = [
    "tools",
    "shared",
    "bootloader",
    "kernel",
    "kernel/volatile_field",
    "kernel/pci_types",
    "kernel/apic",
    "kernel/xhci",
    "kernel/usb-xhci",
]
resolver = "2"

[workspace.dependencies]
uefi = "0.26.0"
uefi-services = "0.23.0"
