[package]
name = "kernel"
version = "1.5.0"
edition = "2021"
authors = ["Paul Sohn <paulsohn@outlook.kr>"]
description = "the kernel part of personal rust implementation of [Mikan OS](https://github.com/uchan-nos/mikanos)"

[dependencies]
shared = { path = "../shared" }
spin = "0.9.8"
x86_64 = "0.14.10"
