[package]
name = "shared"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# freetype-rs = "0.32.0"
uefi = { workspace = true }
volatile = "0.3.0"
