[package]
name = "tools"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
freetype-rs = "0.32.0"
noto-sans-mono-bitmap = "0.2.0"
spin = "0.9.8"
